mybuys.setClient("GUMPS");
mybuys.setOneclkTaupeStyle();
mybuys.enableZones();
mybuys.setOneclkSignupAsImg("http://w.p.mybuys.com/clients/GUMPS/images/exclusive_offers.jpg");
mybuys.setOneclkButtonAlt("Get Exclusive, Insider Offers");
mybuys.setOneclkPrivacyPolicyContent("Privacy Policy<p>Consumer privacy is as important to us as it is to you. This summary is intended to inform you, the end user, about how MyBuys, Gump's service provider for email alerts, handles the information it processes on behalf of Gump's, who uses the service to deliver a better experience for you. MyBuys collects personal information to use in delivering recommendations to you that match your interests. MyBuys doesn't buy or sell your information, and doesn't disclose it to third parties except to deliver its service, and those third parties can only use the data for delivery of the service. MyBuys doesn't collect sensitive information such as credit card numbers, and doesn't install software on your computer or track keystrokes. For the full privacy policy, <a href='http://www.mybuys.com/privacy.html'>click here</a>.");
mybuys.setOneclkWhatsThisContent("What's This<p>Your days of searching for the perfect thing are over. Now, when you see a product you like, simply click this button and enter your email address. We'll take it from there. We'll look for items we think you'll like and alert you via email.<p>Only what you want - and only when there's a reason, such as a new product or a price markdown in your favorite category.<p>And opting out is fast and easy if you decide you're not interested anymore.<p>Give it a try - we think you'll like it.");
mybuys.setStyle('.mblegend','font-family', 'Times New Roman','text-align','left','color','#606060','font-size','15px','font-weight','bold');
mybuys.setStyle('.mbitem','width','125px','padding-right','0px','padding-left','0px','margin-left','10px','margin-right','10px');
mybuys.setStyle('.mbimg','border','solid 1px #999999');
mybuys.setStyle('.mbnamerowspan','text-align','left');
mybuys.setStyle('.mbnamelink:link','font-family', 'Verdana,Geneva,Arial,Helvetica,sans-serif','color','#999999','font-size','11px','font-weight','bold','text-decoration','none');
mybuys.setStyle('.mbnamelink:visited','font-family', 'Verdana,Geneva,Arial,Helvetica,sans-serif','color','#999999','font-size','11px','font-weight','bold','text-decoration','none');
mybuys.setStyle('.mbnamelink:hover','font-family', 'Verdana,Geneva,Arial,Helvetica,sans-serif','color','#999999','font-size','11px','font-weight','bold','text-decoration','underline');
mybuys.setStyle('.mbpricerowleft','float','','text-align','left');
mybuys.setStyle('.mbpricerowright','float','','text-align','left');
mybuys.setStyle('.mbpricelink:link','font-family', 'Verdana,Geneva,Arial,Helvetica,sans-serif','color','#999999','font-size','10px','font-weight','normal','text-decoration','none');
mybuys.setStyle('.mbpricelink:visited','font-family', 'Verdana,Geneva,Arial,Helvetica,sans-serif','color','#999999','font-size','10px','font-weight','normal','text-decoration','none');
mybuys.setStyle('.mbpricelink:hover','font-family', 'Verdana,Geneva,Arial,Helvetica,sans-serif','color','#999999','font-size','10px','font-weight','normal','text-decoration','none');
mybuys.setStyle('.mbpricerowspan','text-align','left');
mybuys.setStyle('.mblistrowleft','float','','text-align','left');
mybuys.setStyle('.mblistrowright','float','','text-align','left');
mybuys.setStyle('.mblistlink:link','font-family', 'Verdana,Geneva,Arial,Helvetica,sans-serif','color','#999999','font-size','10px','font-weight','normal','text-decoration','none');
mybuys.setStyle('.mblistlink:visited','font-family', 'Verdana,Geneva,Arial,Helvetica,sans-serif','color','#999999','font-size','10px','font-weight','normal','text-decoration','none');
mybuys.setStyle('.mblistlink:hover','font-family', 'Verdana,Geneva,Arial,Helvetica,sans-serif','color','#999999','font-size','10px','font-weight','normal','text-decoration','none');
mybuys.setStyle('.mblistrowspan','text-align','left');
mybuys.setStyle('.mbsalerowleft','float','','text-align','left');
mybuys.setStyle('.mbsalerowright','float','','text-align','left');
mybuys.setStyle('.mbsalelink:link','font-family', 'Verdana,Geneva,Arial,Helvetica,sans-serif','color','#B22C1B','font-size','10px','font-weight','normal','text-decoration','none');
mybuys.setStyle('.mbsalelink:visited','font-family', 'Verdana,Geneva,Arial,Helvetica,sans-serif','color','#B22C1B','font-size','10px','font-weight','normal','text-decoration','none');
mybuys.setStyle('.mbsalelink:hover','font-family', 'Verdana,Geneva,Arial,Helvetica,sans-serif','color','#B22C1B','font-size','10px','font-weight','normal','text-decoration','none');
mybuys.setStyle('.mbsalerowspan','text-align','left');

mybuys.useOneclkForExistingSignup(true);
mybuys.applyStyles();
mybuys.setFailOverMsecs(5000);